### ISSUE TITLE
Bilibili网页播放器内白色图标不可见

### ISSUE THREAD

**Issue by XEric7** [flanker/bilibili-dark-mode#1]
不启用拓展：
![屏幕截图 2022-11-29 151756](https://user-images.githubusercontent.com/54767385/204465571-e243d893-7725-41b1-a0ff-a69bc037cead.png)
启用拓展：![屏幕截图 2022-11-29 151559](https://user-images.githubusercontent.com/54767385/204465611-63cae49f-0471-49dd-b6c8-42f9d6418f4d.png)
在启用拓展后，bilibili播放器内的白色图标由于没有反色导致不可见。  
可能的解决方案：可以考虑对bilibili播放器不做反色处理（bilibili播放器的背景色本来就是黑色，进行反色后会呈现白色，反而违背了黑暗模式的设计初衷）。

**Comment by flanker** [comment]
收到。会尽快优化这类。

**Comment by flanker** [comment]
@XEric7 已经在新发布版本中解决（0.0.7），请帮忙确认下 :)

**Comment by XEric7** [comment]
> @XEric7 已经在新发布版本中解决（0.0.7），请帮忙确认下 :)

新版本的效果非常好，感谢开发者的优化。

**Comment by flanker** [comment]
Issue fixed.
