### ISSUE TITLE
直播界面反色 求助

### ISSUE THREAD

**Issue by emdogglee** [flanker/bilibili-dark-mode#12]
你好 如题的bug出现 用的360极速x浏览器

https://live.bilibili.com/888396

https://live.bilibili.com/22747736?broadcast_type=0&is_room_feed=1&spm_id_from=333.999.live_users_card.0.click&live_from=86001

这种都会有问题 反色

**Comment by Harrytion** [comment]
哈哈，MacOS下，Chrome也一样

**Comment by flanker** [comment]
收到，不过我访问直播页面是好的。我猜可能是下面这个设置影响的：

<img width="374" alt="image" src="https://github.com/flanker/bilibili-dark-mode/assets/109811/f3c057c9-e41f-4189-99b7-76c0e54a14a8">

能看一下你们这里的设置吗？  @Harrytion @emdogglee

**Comment by flanker** [comment]
我复现了问题，当启用了「深色模式」之外的其他设置时，会有颜色不正确。

已经在新版本修复（0.2.2），已提交 chrome 审核。

**Comment by flanker** [comment]
已经更新发布。请帮忙确认下问题是否解决。多谢 @Harrytion @emdogglee

**Comment by emdogglee** [comment]
> 已经更新发布。请帮忙确认下问题是否解决。多谢 @Harrytion @emdogglee

你好 反色解决了 就是网页全屏的时候 边缘的黑色还是会有反色的问题 如图
![Uploading 恐怖游戏 迷离诡夜 直播 - 不死鸟总监 - 哔哩哔哩直播，二次元弹幕直播平台.png…]()

**Comment by emdogglee** [comment]
![恐怖游戏 迷离诡夜 直播 - 不死鸟总监 - 哔哩哔哩直播，二次元弹幕直播平台](https://github.com/flanker/bilibili-dark-mode/assets/173607604/8b7b5771-7a76-46af-895e-cb831daa6f0d)
![Uploading 360截图20240703232845670.jpg…]()

**Comment by emdogglee** [comment]
设置是正常的 跟随系统或者直接设置黑色都有问题

**Comment by emdogglee** [comment]
![Uploading 360截图20240703233235190.jpg…]()

**Comment by flanker** [comment]
@emdogglee 收到，我尽快修复下

**Comment by emdogglee** [comment]
而且现在有新问题 评论区的图片也反色了
![8](https://github.com/flanker/bilibili-dark-mode/assets/173607604/a39eab68-72c4-45b8-98cc-c0ff693bddb3)
![9](https://github.com/flanker/bilibili-dark-mode/assets/173607604/0d75b035-0c45-49f0-b8f8-8ca4012a6277)

**Comment by flanker** [comment]
@emdogglee 直播页面、评论区 都再次优化了一下，已经发布了新版本，帮忙确认下哈

**Comment by emdogglee** [comment]
评论区输入框可以再看看哦 还是有点反色
![360截图20240718145338324](https://github.com/user-attachments/assets/66df114d-455e-4af4-9f5a-5be992b0dfc3)

**Comment by flanker** [comment]
> 评论区输入框可以再看看哦 还是有点反色 ![360截图20240718145338324](https://private-user-images.githubusercontent.com/173607604/349846480-66df114d-455e-4af4-9f5a-5be992b0dfc3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzQ0MzcsIm5iZiI6MTcyMTUzNDEzNywicGF0aCI6Ii8xNzM2MDc2MDQvMzQ5ODQ2NDgwLTY2ZGYxMTRkLTQ1NWUtNGFmNC05ZjVhLTViZTk5MmIwZGZjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwMzU1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOThhNDVkZmJjZjk5NzJiZmEwM2QyNTdhZGY3NDUzNjY2MzQyMWE3YTQ4MmJiNTZlMjE1YTg2ZDg5OTQyYjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4xtLnNA0YF5w3ct_MvJYWPB9T-05rCq-9mqhk30EoIU)

已经发了一个 fix ，等待审核

**Comment by flanker** [comment]
> 评论区输入框可以再看看哦 还是有点反色 ![360截图20240718145338324](https://private-user-images.githubusercontent.com/173607604/349846480-66df114d-455e-4af4-9f5a-5be992b0dfc3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Njc5MTcsIm5iZiI6MTcyMTU2NzYxNywicGF0aCI6Ii8xNzM2MDc2MDQvMzQ5ODQ2NDgwLTY2ZGYxMTRkLTQ1NWUtNGFmNC05ZjVhLTViZTk5MmIwZGZjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQxMzEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTk3ZTc0ZDhkNDQwY2Q5YTg0N2JkZTBkMjVjMzk1YWY0Y2ZlZDllYmI1ZjIxMWE2MDRmYzllNDM0MjFlMzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tZiEbyOplS4G_ng-ahdZGIKjXb7YXDirPvVF0ou25yU)

hello 评论区的反色已经修复了，已经发布了版本（0.3.0）请帮忙检查下 @emdogglee

**Comment by Harrytion** [comment]
![image](https://github.com/user-attachments/assets/970f2244-4577-41b6-a230-ce30f7a709cf)
全屏还是有问题，直播全屏，MACOS 系统 13.6 ，Chrome最新版本  @flanker

**Comment by flanker** [comment]
> ![image](https://private-user-images.githubusercontent.com/18097932/352810512-970f2244-4577-41b6-a230-ce30f7a709cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzczNjcsIm5iZiI6MTcyMjE3NzA2NywicGF0aCI6Ii8xODA5NzkzMi8zNTI4MTA1MTItOTcwZjIyNDQtNDU3Ny00MWI2LWEyMzAtY2UzMGY3YTcwOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE0MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNGEwNTlkZWFhYjRlMmVmYmFmZjVmM2JlNjRiNjgxNDIwZDUzNWZlZDY5NzU2YjMxMTBkMDNjZGUyOTEzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkCITUtkecqy7xW9dR6tF1AMYV0Fte-3Lb1V0bdsaSM) 全屏还是有问题，直播全屏，MACOS 系统 13.6 ，Chrome最新版本 @flanker

这个网页的链接可以发一下吗？我一直没有试出来，感觉不是普通的直播页面的全屏

**Comment by Harrytion** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18097932/352810512-970f2244-4577-41b6-a230-ce30f7a709cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzczNjcsIm5iZiI6MTcyMjE3NzA2NywicGF0aCI6Ii8xODA5NzkzMi8zNTI4MTA1MTItOTcwZjIyNDQtNDU3Ny00MWI2LWEyMzAtY2UzMGY3YTcwOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE0MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNGEwNTlkZWFhYjRlMmVmYmFmZjVmM2JlNjRiNjgxNDIwZDUzNWZlZDY5NzU2YjMxMTBkMDNjZGUyOTEzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkCITUtkecqy7xW9dR6tF1AMYV0Fte-3Lb1V0bdsaSM) 全屏还是有问题，直播全屏，MACOS 系统 13.6 ，Chrome最新版本 @flanker
> 
> 这个网页的链接可以发一下吗？我一直没有试出来，感觉不是普通的直播页面的全屏

@flanker  LPL直播

**Comment by nick-cjyx9** [comment]
反色问题仍存在

![image](https://github.com/user-attachments/assets/a4aedd94-2289-4a44-8d7c-33ae7fee15f1)

```
Arc | 127.0.6533.120 (正式版本) （64 位）
-- | --
修订版本 | c51f2916e4a14157c276fd33c8bfb24155aac1ad-refs/branch-heads/6533@{#2000}
操作系统 | Windows 11 Version 23H2 (Build 22631.4037)
JavaScript | V8 12.7.224.18
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
命令行 | "C:\Program Files\WindowsApps\TheBrowserCompany.Arc_1.15.0.43650_x64__ttt1ap7aakyb4\Arc.exe" --flag-switches-begin --flag-switches-end
可执行文件路径 | C:\Program Files\WindowsApps\TheBrowserCompany.Arc_1.15.0.43650_x64__ttt1ap7aakyb4\Arc.exe
个人资料路径 | C:\Users\cjyx9\AppData\Local\Packages\TheBrowserCompany.Arc_ttt1ap7aakyb4\LocalCache\Local\Arc\User Data\Default
使用中的变体 | 5e3a236d-59e286d0
```

**Comment by flanker** [comment]
fixed
