### ISSUE TITLE
评论区颜色和字体颜色好像都是白色，导致看不到，只有选中才能看到

### ISSUE THREAD

**Issue by lixcamel** [flanker/bilibili-dark-mode#15]
![image](https://github.com/user-attachments/assets/06a573b8-c1b1-465e-80b5-87d810f49adc)

**Comment by lixcamel** [comment]
刚刚好像又发现了一个bug：直播页面
![Screenshot 2024-07-19 135454](https://github.com/user-attachments/assets/d3c38534-648f-47d9-b1eb-044ccdd7869e)
下会反色

**Comment by flanker** [comment]
> 刚刚好像又发现了一个bug：直播页面 ![Screenshot 2024-07-19 135454](https://private-user-images.githubusercontent.com/73375793/350395577-d3c38534-648f-47d9-b1eb-044ccdd7869e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzAxOTksIm5iZiI6MTcyMTUyOTg5OSwicGF0aCI6Ii83MzM3NTc5My8zNTAzOTU1NzctZDNjMzg1MzQtNjQ4Zi00N2Q5LWIxZWItMDQ0Y2NkZDc4NjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAyNDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNWI3Y2FlMGUxNDkyMjI5Mjc4MDM5Yzc0ZTFlNDQyYzdjMjZlNmE5NDhkMjllZDJmNDY3NTE4YjIyMmMzZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h6gRonnm0b6dgERwuLBTyQoPW1DcJFbYimfc0lpP9AY) 下会反色

你好 @lixcamel  这个直播反色的可以给一个链接吗？

另外你用的是什么浏览器，插件是什么版本的？因为我这里貌似没有遇到直播反色的问题。

多谢

**Comment by flanker** [comment]
> ![image](https://private-user-images.githubusercontent.com/73375793/348292591-06a573b8-c1b1-465e-80b5-87d810f49adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzQ0MTIsIm5iZiI6MTcyMTUzNDExMiwicGF0aCI6Ii83MzM3NTc5My8zNDgyOTI1OTEtMDZhNTczYjgtYzFiMS00NjVlLTgwYjUtODdkODEwZjQ5YWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAzNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MzAzZTY1MjljZGNlMzBlMjIxN2M4ZDdjNTJiY2UyY2M5MDBkYTlhOTM3YzQ3YjVjYzMwZjQ3OTQwMjlkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.maZTODz_kXiFivyyNaaQ-USqr6rYWb8HvL59yJwbSIA)

已经发了一个 fix ，等待审核

**Comment by lixcamel** [comment]
> > 刚刚好像又发现了一个bug：直播页面 ![Screenshot 2024-07-19 135454](https://private-user-images.githubusercontent.com/73375793/350395577-d3c38534-648f-47d9-b1eb-044ccdd7869e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzAxOTksIm5iZiI6MTcyMTUyOTg5OSwicGF0aCI6Ii83MzM3NTc5My8zNTAzOTU1NzctZDNjMzg1MzQtNjQ4Zi00N2Q5LWIxZWItMDQ0Y2NkZDc4NjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAyNDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNWI3Y2FlMGUxNDkyMjI5Mjc4MDM5Yzc0ZTFlNDQyYzdjMjZlNmE5NDhkMjllZDJmNDY3NTE4YjIyMmMzZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h6gRonnm0b6dgERwuLBTyQoPW1DcJFbYimfc0lpP9AY) 下会反色
> 
> 你好 @lixcamel 这个直播反色的可以给一个链接吗？
> 
> 另外你用的是什么浏览器，插件是什么版本的？因为我这里貌似没有遇到直播反色的问题。
> 
> 多谢

explorer：Chrome 126.0.6478.128（正式版本） （64 位）
plugin：0.3.0
直播是 瓶子君152的直播间，直播间号42062
（个人感觉是因为Valorant的电竞赛事直播，b站重写了页面导致的，现在没有这个页面了）

**Comment by flanker** [comment]
@lixcamel 评论区的反色已经修复了，已经发布了版本（0.3.0）请帮忙检查下

**Comment by lixcamel** [comment]
> @lixcamel 评论区的反色已经修复了，已经发布了版本（0.3.0）请帮忙检查下

已解决，感谢
