### ISSUE TITLE
[Bug] Color of Emojis in comment being reverted incorrectly

### ISSUE THREAD

**Issue by nfnfgo** [flanker/bilibili-dark-mode#17]
# Devices & Environment Info

- Plugin Version: `0.3.0`
- Browser: `Microsoft Edge`

# Issue

The **color of the emojis in comment block is inverted where it shouldn't be**. Check out following screenshot for details.

![image](https://github.com/user-attachments/assets/40a3b67a-8b4e-4fb6-bb89-e002b31118ea)
![image](https://github.com/user-attachments/assets/3d151bd5-812a-4690-a425-0d6a9b4eef63)
![image](https://github.com/user-attachments/assets/a53c8542-124f-4733-a15d-b8e71819e8fa)

**Comment by flanker** [comment]
已经提交更新，0.3.1 版本。

**Comment by flanker** [comment]
fixed. thanks for feedback.
