### ISSUE TITLE
在剧集的播放页面，底部评论字体未反色（显示为黑色），导致不可见

### ISSUE THREAD

**Issue by XEric7** [flanker/bilibili-dark-mode#2]
# 存在问题的部分页面的链接
https://www.bilibili.com/bangumi/play/ep706666
https://www.bilibili.com/bangumi/play/ep704473
# 截图：
![屏幕截图 2023-01-18 132937](https://user-images.githubusercontent.com/54767385/213091836-f69b205a-1805-4a1a-b071-eed7a6d0dcd9.png)
（在截图中，所有评论由于显示为黑色，均不可见）
# 其他信息
浏览器版本：Edge 109.0.1518.55

**Comment by flanker** [comment]
收到反馈。

**Comment by flanker** [comment]
已提交 Chrome 和 Edge 的 Web Store 待审核。

**Comment by flanker** [comment]
@XEric7 已经修复。新版本（0.0.9）已经发布

**Comment by XEric7** [comment]
> @XEric7 已经修复。新版本（0.0.9）已经发布

新版本已经修复了这个问题，
感谢开发者的优化。
