### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Jiang10086** [flanker/bilibili-dark-mode#7]
![image](https://github.com/flanker/bilibili-dark-mode/assets/67213568/ab9169dc-d9a0-4d75-8391-695c01e282a1)
- 如图，[B 站历史记录页面](https://www.bilibili.com/account/history)的搜索框没有适配夜间模式
- 背景和文字是纯黑和纯白，对比度太高不太易读，关于配色可参考：[为什么「暗色模式」不应采用纯黑背景？这是谷歌的理由](https://sspai.com/post/56401)
- 
![image](https://github.com/flanker/bilibili-dark-mode/assets/67213568/19e1c2bd-6bde-4c7a-a502-f2d79ebd3781)
在首页视频封面下面都蒙上了一层「白雾」，有点影响观感。

虽然这么说，还是感谢为开源社区做的贡献，祝好。

**Comment by flanker** [comment]
感谢支持。这几点我看看怎么优化。

and 这个插件的确实现方式非常简单，所以在性能和表现上有很多需要优化的地方。

**Comment by flanker** [comment]
「[B 站历史记录页面](https://www.bilibili.com/account/history)的搜索框没有适配夜间模式」 这个问题已经在新发布的 0.0.11 中修复

**Comment by flanker** [comment]
@Jiang10086 「在首页视频封面下面都蒙上了一层「白雾」，有点影响观感。」

这点已经优化（新发布 0.12 版本）。首页视频封面的 mask 改为黑色底、白色字

**Comment by flanker** [comment]
issue closed
