### ISSUE TITLE
头像反色和直播页面问题

### ISSUE THREAD

**Issue by xinjiangdapanji** [flanker/bilibili-dark-mode#8]
1. 头像反色影响不大

2. 主要是直播页面可以停用darkmode了，官方自带了关灯模式，而且直播页面花里胡哨的东西挺多的（就比如直播播放进度条和普通视频进度条不一样），适配麻烦😘

**Comment by flanker** [comment]
第二个问题已经优化，当在直播页面开启了官方深色模式后，就在该页面停用本插件的深色模式。已提交 chrome store 审核。

**Comment by xinjiangdapanji** [comment]
非常好的修改 感谢你的贡献 爱来自中国♥

**Comment by flanker** [comment]
Thanks. Chrome 已经发布 0.0.13
